name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build
        run: bash scripts/build.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            zig-out/dist/linux/docker-tags_linux_x86_64.zip
            zig-out/dist/macos/docker-tags_macos_aarch64.zip
            zig-out/dist/windows/docker-tags_windows_x86_64.zip
          generate_release_notes: true
          draft: true
